export interface User {
  id: number;
  unique_id: string;
  name: string;
  email: string;
  phone: string;
  skype: string;
  whats_app: string;
  age: string;
  gender: string;
  dob: string;
  country: string;
  province: string;
  city: string;
  details: string;
  language: string;
  time_zone: string;
  role: string;
  profile_image: string;
  email_verified_at: string;
  isVerified: string;
  status: string;
  notification: string;
  rate: string;
  domain_id: string;
  token: string;
}
export type workersType = {
  full_name: string;
  father_name: string;
  contact_email: string;
  phone_number: string;
  secondary_phone_number: string;
  branch_id: string;
  salary: string;
  full_address: string;
  state: string;
  city: string;
  zip_code: string;
  cnic_front: string;
  cnic_back: string;
  account_maintenance_certificate: string;
  blank_check: string;
  reference_1_name: string;
  reference_1_number: string;
  reference_1_cnic: string;
  reference_2_name: string;
  reference_2_number: string;
  reference_2_cnic: string;
  profile_image: string;
  role: string;
  status: string;
  is_verified: string;
  notification: string;
};
export type BranchesType = {
  id: string;
  unique_id: string;
  name: string;
  branch_contact_no: string;
  branch_address: string;
  open: number;
  closed: number;
  others: number;
  status: string;
  created_at: string;
  updated_at: string;
};
export type BrandsType = {
  id: string;
  unique_id: string;
  name: string;
  log: strig;
  open: number;
  closed: number;
  others: number;
  status: string;
  created_at: string;
  updated_at: string;
};
export type CategoriesType = {
  id: string;
  unique_id: string;
  name: string;
  slug: string;
  description: string;
  keywords: string;
  image: string;
  hero_image: string;
  open: number;
  closed: number;
  others: number;
  status: string;
  created_at: string;
  updated_at: string;
};
export type ServicesType = {
  id: string;
  unique_id: string;
  category_id: string;
  category_name: string;
  name: string;
  slug: string;
  description: string;
  keywords: string;
  image: string;
  hero_image: string;
  open: number;
  closed: number;
  others: number;
  status: string;
  created_at: string;
  updated_at: string;
};
export type SubServicesType = {
  id: string;
  unique_id: string;
  category_id: string;
  service_id: string;
  category_name: string;
  service_name: string;
  name: string;
  slug: string;
  price: string;
  discount: string;
  description: string;
  keywords: string;
  image: string;
  hero_image: string;
  open: number;
  closed: number;
  others: number;
  status: string;
  created_at: string;
  updated_at: string;
};
export type ComplaintsType = {
  id: number;
  applicant_name: string;
  applicant_email: string;
  applicant_phone: string;
  applicant_whatsapp: string;
  applicant_adress: string;
  complain_num: string;
  complaint_heading: string;
  description: string;
  status: string;
  created_at: string;
  updated_at: string;
};
export type ComplaintDetailsType = {
  id: number;
  complaint_id: number;
  brand_id: string;
  branch_id: string;
  company_complaint_no: string | null;
  product: string;
  model: string;
  serial_number_ind: string | null;
  serial_number_oud: string | null;
  mq_nmb: string | null;
  p_date: string | null;
  complete_date: string | null;
  amount: number | null;
  technician: string | null;
  status: string;
  complaint_type: string;
  provided_services: string;
  extra: string | null;
  images: string | null;
  created_at: string;
  updated_at: string;
};
export type DomainsType = {
  id: string;
  unique_id: string;
  value: string;
  clicks: number;
  conversions: number;
  cvr: number;
  progress: number;
  chart_data: array;
  status: string;
  created_at: string;
  updated_at: string;
};
export type dataTypeIds = {
  value: string;
  label: string;
  image: string;
};
export type TrackerType = {
  id: string;
  unique_id: string;
  name: string;
  param: string;
  value: string;
  clicks: number;
  conversions: number;
  cvr: number;
  status: string;
  visiblity: string;
  created_at: string;
  updated_at: string;
};
export type OfferType = {
  id: string;
  unique_id: string;
  name: string;
  title: string;
  description: string;
  keywords: string;
  offer_name: string;
  image: string;
  age: string;
  rate: string;
  encryption: string;
  network_id: string;
  domain_id: string;
  category_id: string;
  urls: [];
  countries: string;
  proxy: string;
  clicks: string;
  conversions: string;
  cvr: string;
  url: string;
  status: string;
  appliableFor: string;
};
export type UserType = {
  id: string;
  unique_id: string;
  name: string;
  profile_pic: string;
  username: string;
  email: string;
  phone: string;
  age: string;
  rate: string;
  clicks: string;
  conversions: string;
  cvr: string;
  role: string;
  manager_username: string;
  admin_username: string;
  created_at: string;
  updated_at: string;
  status: string;
};

type CountryType = {
  id: number;
  name: string;
  unique_id: string;
  iso2: string;
};
type SettingsType = {
  id: number;
  key: string;
  value: string;
  description: string;
  status: string;
  created_at: string;
  updated_at: string;
};
type ClickType = {
  id: number;
  created_at: string;
  updated_at: string;
  click_id: number;
  offer_id: string;
  network_id: string;
  tracker_id: string;
  domain_id: string;
  user_id: string;
  manager_id: any;
  admin_id: any;
  ip_address: string;
  source_id: string;
  country: string;
  city: string;
  device: string;
  device_version: any;
  browser: string;
  version: any;
  user_agent: any;
  status: string;
};
interface MetaDataType {
  title: string;
  description: string;
  image: string;
  keywords: string;
  author: string;
  canonical: string;
}
type FetchResult<T> = {
  data: T | null;
  error: Error | null;
  isLoading: boolean;
};
